CREATE TABLE proxy (
	principal INTEGER NOT NULL,
	proxy INTEGER NOT NULL,
	bits INTEGER NOT NULL DEFAULT(0),
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	FOREIGN KEY (principal) REFERENCES principal(id) ON DELETE CASCADE,
	FOREIGN KEY (proxy) REFERENCES principal(id) ON DELETE CASCADE
);
