.\"	$Id$
.\"
.\" Copyright (c) 2015 Kristaps Dzonsons <kristaps@bsd.lv>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: May 4 2015 $
.Dt KCALDAV.PASSWD 1
.Os
.Sh NAME
.Nm kcaldav.passwd
.Nd change kcaldav user information
.\" .Sh LIBRARY
.\" For sections 2, 3, and 9 only.
.\" Not used in OpenBSD.
.Sh SYNOPSIS
.Nm kcaldav.passwd
.Op Fl Cn
.Op Fl d Ar directory
.Op Fl e Ar email
.Op Fl f Ar caldir
.Op Fl u Ar user
.Op Ar resource...
.Sh DESCRIPTION
The
.Nm
program updates the database for an instance of
.Xr kcaldav 8 .
By default, it changes
.Pa @CALDIR@/kcaldav.db
for the user with the currently logged-in username, prompting for the
existing passwords when it does so.
Its arguments are as follows:
.Bl -tag -width Ds
.It Fl C
Create a new user with a default email (see
.Fl e )
and calendar (see
.Fl d ) .
The current real user (via
.Xr getuid 2 )
must match the password database owner to use this option, or the real
user must be root.
Does nothing if a user by that name already exists.
If the database does not exist, creates it with the current real user
set as the database owner.
.It Fl n
Do not change the user password, but only the user attributes (e.g.,
.Fl e Ar email ) .
.It Fl d Ar directory
Add a calendar directory for the requested user, or set the default
directory if specified with
.Fl C .
If not specified when
.Fl C ,
is specified the directory
.Dq calendar
is used.
If not using
.Fl C
and the collection already exists, it is a no-op.
.It Fl e Ar email
Change the e-mail address of the requested user.
This can be any email address.
If unspecified and the new user is created with
.Fl C ,
this defaults to
.Ar <user>@<hostname> ,
where the hostname is looked up with
.Xr gethostname 3
and defaults to localhost if there's no hostname set.
.It Fl f Ar passdir
Specify an alternative database directory.
.It Fl u Ar user
Use an alternative username.
The current real user (via
.Xr getuid 2 )
must match the password file owner to use this option, or the real user
must be root.
.It Ar resource
A list of iCalendar resources to add to the calendar collection
.Fl d
or
.Dq calendar
if none was specified.
The name of the calendar is the filename component of
.Ar resource .
.El
.Pp
.Nm
is designed for use by a single user or by a set of users on a UNIX server.
To achieve the latter, one may use the set-user-ID or set-group-ID bits on the
.Nm
binary, disallowing users direct access to the file except by way of
.Nm .
See the
.Sx EXAMPLES
section for possibilities.
.Pp
Always remember to set the database to be read-writable by the web server!
.\" .Sh IMPLEMENTATION NOTES
.\" Not used in OpenBSD.
.\" .Sh RETURN VALUES
.\" For sections 2, 3, and 9 function return values only.
.\" .Sh ENVIRONMENT
.\" For sections 1, 6, 7, and 8 only.
.\" .Sh FILES
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
To have a calendar database usable by system users, but restricted to the
.Nm
binary, you might use a dummy
.Dq kcaldav
user owning the file.
.Bd -literal -offset indent
# chown kcaldav @PREFIX@/bin/kcaldav.passwd
# chmod u+s @PREFIX@/bin/kcaldav.passwd
# sudo -u kcaldav kcaldav.passwd -C -u <user>
.Ed
.Pp
System users may then run
.Nm
as themselves.
.Pp
To add calendars to a principal, try
.Pp
.Dl % kcaldav.passwd -n -d newcalendar
.Pp
To add resources to a new calendar or existing, try
.Pp
.Dl % kcaldav.passwd -n -d newcalendar file1.ics file2.ics
.\" .Sh DIAGNOSTICS
.\" For sections 1, 4, 6, 7, 8, and 9 printf/stderr messages only.
.\" .Sh ERRORS
.\" For sections 2, 3, 4, and 9 errno settings only.
.Sh SEE ALSO
.Xr kcaldav 8
.\" .Sh STANDARDS
.\" .Sh HISTORY
.\" .Sh AUTHORS
.\" .Sh CAVEATS
.\" .Sh BUGS
.\" .Sh SECURITY CONSIDERATIONS
.\" Not used in OpenBSD.
