.Dd $Mdocdate: March 29 2015 $
.Dt KCALDAV.CONF 5
.Os
.Sh NAME
.Nm kcaldav.conf
.Nd kcaldav collection configuration
.\" .Sh LIBRARY
.\" For sections 2, 3, and 9 only.
.\" Not used in OpenBSD.
.\" .Sh SYNOPSIS
.\" .Nm kcaldav
.\" .Op Fl options
.\" .Ar
.Sh DESCRIPTION
The
.Nm
configuration, which is always named
.Nm kcaldav.conf ,
defines properties for a CalDAV collection.
It must be exist and be well-formed for each collection (file-system
directory), else that collection is not considered by
.Xr kcaldav 8 .
.Pp
The configuration file is line-based, with blank lines discarded.
See
.Xr fparseln 3
for implementation details.
At any point in the line you may begin a comment with the
.Qq #
character: the remainder of the line will be thrown away.
You may escape the comment token with a backslash.
Line endings may also be escaped with a backslash.
.Pp
Each line consists of a token and value separated by an equal sign (and
possibly white-space), such as
.Bd -literal -offset indent
privilege = kristaps READ WRITE
email-address-set = kristaps@bsd.lv
.Ed
.Pp
Trailing and leading line white-space are discarded.
.Pp
The following configuration tokens are accepted:
.Bl -tag -width Ds
.It email-address-set
This is mandatory.
It consists of the collection owner's e-mail address.
.It displayname
This is the collection's natural-language name.
It may be in UTF-8.
It defaults to an empty string.
.It privilege
Define access privileges for a named principal.
This accepts the principal name then a space-separated list of
privileges.
The principal name may be
.Qq _anonymous
for the anonymous principal (no credentials).
Privileges are case insensitive and may be
.Qq NONE ,
.Qq READ ,
.Qq DELETE ,
or
.Qq WRITE.
If at any time
.Qq NONE
occurs, or the set of privileges is empty, the principal is assigned no
privileges.
You may use the
.Qq ALL
token to assign all privileges.
.El
.\" .Sh CONTEXT
.\" For section 9 functions only.
.\" .Sh IMPLEMENTATION NOTES
.\" Not used in OpenBSD.
.\" .Sh RETURN VALUES
.\" For sections 2, 3, and 9 function return values only.
.\" .Sh ENVIRONMENT
.\" For sections 1, 6, 7, and 8 only.
.\" .Sh FILES
.\" .Sh EXIT STATUS
.\" For sections 1, 6, and 8 only.
.\" .Sh EXAMPLES
.\" .Sh DIAGNOSTICS
.\" For sections 1, 4, 6, 7, 8, and 9 printf/stderr messages only.
.\" .Sh ERRORS
.\" For sections 2, 3, 4, and 9 errno settings only.
.Sh SEE ALSO
.Xr fparseln 3 ,
.Xr kcaldav 8
.\" .Sh STANDARDS
.\" .Sh HISTORY
.\" .Sh AUTHORS
.\" .Sh CAVEATS
.\" .Sh BUGS
.\" .Sh SECURITY CONSIDERATIONS
.\" Not used in OpenBSD.
