.\"	$Id$
.\"
.\" Copyright (c) 2015 Kristaps Dzonsons <kristaps@bsd.lv>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt KCALDAV.PASSWD 1
.Os
.Sh NAME
.Nm kcaldav
.Nd change kcaldav user information
.\" .Sh LIBRARY
.\" For sections 2, 3, and 9 only.
.\" Not used in OpenBSD.
.Sh SYNOPSIS
.Nm kcaldav.passwd
.Op Fl cn
.Op Fl d Ar homedir
.Op Fl f Ar passdir
.Op Ar user
.Sh DESCRIPTION
The
.Nm
program updates the
.Xr kcaldav.passwd.5
file for an instance of
.Xr kcaldav 8 .
By default,
.Nm
will change the password for an existing user
.Ar user
in the
.Xr kcaldav 8
calendar root
.Pa @CALDIR@ .
Its arguments are as follows:
.Bl -tag -width Ds
.It Fl c
Create a new user.
Does nothing if a user by that name already exists.
.It Fl n
Do not change the user password, but only the user attributes (e.g.,
.Fl d ) .
.It Fl d Ar homedir
Specify the home directory (within the
.Xr kcaldav 8
file-system root) of
.Ar user .
If unspecified and a new user is created with
.Fl c ,
this defaults to
.Pf / Ar user .
This must be an absolute path.
.It Fl f Ar passdir
Specify an alternative password directory.
.It Ar user
The user to be created or modified.
.El
.Pp
This utility should always be used to edit the password file: it manages
locking and sanity-checks input.
.\" .Sh IMPLEMENTATION NOTES
.\" Not used in OpenBSD.
.\" .Sh RETURN VALUES
.\" For sections 2, 3, and 9 function return values only.
.\" .Sh ENVIRONMENT
.\" For sections 1, 6, 7, and 8 only.
.\" .Sh FILES
.Sh EXIT STATUS
.Ex -std
.\" .Sh EXAMPLES
.\" .Sh DIAGNOSTICS
.\" For sections 1, 4, 6, 7, 8, and 9 printf/stderr messages only.
.\" .Sh ERRORS
.\" For sections 2, 3, 4, and 9 errno settings only.
.Sh SEE ALSO
.Xr readpassphrase 3 ,
.Xr kcaldav.passwd 5 ,
.Xr kcaldav 8
.\" .Sh STANDARDS
.\" .Sh HISTORY
.\" .Sh AUTHORS
.\" .Sh CAVEATS
.\" .Sh BUGS
.\" .Sh SECURITY CONSIDERATIONS
.\" Not used in OpenBSD.
