.\"	$Id$
.\"
.\" Copyright (c) 2015 Kristaps Dzonsons <kristaps@bsd.lv>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: April 4 2015 $
.Dt KCALDAV 8
.Os
.Sh NAME
.Nm kcaldav
.Nd simple CalDav server
.\" .Sh LIBRARY
.\" For sections 2, 3, and 9 only.
.\" Not used in OpenBSD.
.Sh SYNOPSIS
.Nm kcaldav
.Op Ar caldir
.Sh DESCRIPTION
The
.Nm
CGI program minimally implements CalDAV, with an emphasis on strong
authorisation and simplicity.
To use
.Nm ,
you'll need to first populate the calendar root directory
.Ar caldir .
This is relative to the CGI script's file-system root, defaulting to
.Pa @CALDIR@ .
This requires a
.Xr kcaldav.passwd 5
password file and a
.Xr kcaldav.conf 5
configuration file for each calendar collection.
.Pp
Once finished, you can point your calendar client to the owned
collection within the calendar root.
.Pp
For example, assume the script has been installed into
.Pa /var/www/cgi-bin
and is reachable at
.Pp
.D1 http://localhost/cgi-bin/kcaldav
.Pp
Moreover, assume your calendar root
.Pa @CALDIR@
contains a
.Xr kcaldav.passwd 5
and you have installed a single collection at
.Pa @CALDIR@/kristaps
consisting of
.Pa kcaldav.conf
and some calendars.
.Bd -unfilled -offset indent
.Pa @CALDIR@/kcaldav.passwd
.Pa @CALDIR@/kristaps
.Pa @CALDIR@/kristaps/kcaldav.conf
.Pa @CALDIR@/kristaps/vevent-001.ics
.Pa @CALDIR@/kristaps/vevent-002.ics
.Ed
.Pp
You can then point your browser to the following:
.Pp
.D1 http://localhost/cgi-bin/kcaldav/kristaps/
.Pp
Note the trailing slash, otherwise the request is interpreted as for a
resource (file), not a collection (directory).
.\" .Sh CONTEXT
.\" For section 9 functions only.
.Sh IMPLEMENTATION NOTES
Internally,
.Nm
maintains file consistency by using file locks and temporary files.
When new resources are submitted, the new resource is always written
into a temporary file, which is the existing filename with a leading
dot.
(Leading-dot files are thus always ignored when accessing files and
disallowed for resource submission.)
By writing into a temporary file,
.Nm
can safely check for file-system limits.
.Pp
After writing, the requested file is uniquely opened and exclusively
locked, replaced with the temporary file, then unlocked.
.Pp
If the requested file exists and is meant for overwrite, the existing
file is opened and exclusively locked, its digest checked for
consistency, then the new file replaced before unlocking.
.Pp
Resource read-access is simpler: files are opened with shared locks.
This allows simultaneous read-access whilst protecting file
modification.
.Pp
This behaviour depends upon standards-defined behaviour of
.Xr open 2
with
.Dv O_EXCL ,
.Dv O_SHLOCK
and
.Dv O_EXLOCK ;
.Xr flock 2
with
.Dv LOCK_EX
and
.Dv LOCK_SH ;
and
.Xr rename 2 .
.\" Not used in OpenBSD.
.\" .Sh RETURN VALUES
.\" For sections 2, 3, and 9 function return values only.
.\" .Sh ENVIRONMENT
.\" For sections 1, 6, 7, and 8 only.
.Sh FILES
The following files are required in the calendar root directory.
.Bl -tag -width Ds
.It Pa /kcaldav.passwd
Authorisation for all principals.
See
.Xr kcaldav.passwd 5 .
.It Pa /<collection>/kcaldav.conf
Given a directory path
.Pa <collection> ,
the
.Pa kcaldav.conf
file defines the collection properties.
See
.Xr kcaldav.conf 5 .
.El
.Pp
The following files may be created during runtime:
.Bl -tag -width Ds
.It Pa /<collection>/kcaldav.ctag
A cache file for the collection's ctag (entity tag for the collection).
This is automatically created and updated.
.El
.\" .Sh EXIT STATUS
.\" For sections 1, 6, and 8 only.
.\" .Sh EXAMPLES
.\" .Sh DIAGNOSTICS
.\" For sections 1, 4, 6, 7, 8, and 9 printf/stderr messages only.
.\" .Sh ERRORS
.\" For sections 2, 3, 4, and 9 errno settings only.
.\" .Sh SEE ALSO
.\" .Xr foobar 1
.Sh STANDARDS
The
.Nm
utility minimally implements RFC 4918 (WebDAV), RFC 4791 (CalDAV), and
of course RFC 2616 (HTTP).
It also implements the following extensions:
.Bl -tag -width Ds
.It RFC 7232
Conditional HTTP responses (etag,
.Qq If-Match ,
etc.).
.It RFC 2617
.Qq Digest
authentication of all users.
.It caldav-ctag-02
The
.Qq ctag
Calendar Server Extension.
.It RFC 3744
ACL queries on the authenticated principal (not ACEs).
.It RFC 5397
The current principal address.
.It RFC 4331
Available and used bytes in the collection file-system via
.Xr fstatfs 2 .
.El
.\" .Sh HISTORY
.\" .Sh AUTHORS
.Sh CAVEATS
Quotas (via
.Xr quotactl 2 )
are not yet supported because the library interface is too damn
complicated.
.\" .Sh BUGS
.\" .Sh SECURITY CONSIDERATIONS
.\" Not used in OpenBSD.
