.\"	$Id$
.\"
.\" Copyright (c) 2015 Kristaps Dzonsons <kristaps@bsd.lv>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt LIBKCALDAV 3
.Os
.Sh NAME
.Nm libkcaldav
.Nd simple CalDav server library
.Sh LIBRARY
.Lb kcaldav
.Sh SYNOPSIS
.In time.h
.In libkcaldav.h
.Ft void
.Fo caldav_free
.Fa "struct caldav *p"
.Fc
.Ft "struct caldav *"
.Fo caldav_parse
.Fa "const char *buf"
.Fa "size_t bufsz"
.Fc
.Ft void
.Fo ical_free
.Fa "struct ical *p"
.Fc
.Ft "struct ical *"
.Fo ical_parse
.Fa "const char *file"
.Fa "const char *buf"
.Fa "size_t bufsz"
.Fc
.Sh DESCRIPTION
The
.Nm libkcaldav
library parses CalDAV and iCalendar files.
This documentation is only a stub: it is yet to be written.
.Sh STANDARDS
The
.Nm libkcaldav
library minimally implements RFC 4918 (WebDAV), RFC 4791 (CalDAV),
caldav-ctag-02 (CalDAV ctags), RFC 3744 (only the ACL component), RFC 5397
(current principal address), and RFC 4331 (file-system quota).
